In [101]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OrdinalEncoder,OneHotEncoder,LabelEncoder,StandardScaler,MinMaxScaler

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer


from sklearn.linear_model import LogisticRegression

In [102]:
url = "https://raw.githubusercontent.com/MuktadirHQ/AIML-Expert-With-Phitron/refs/heads/main/Machine%20Learning/WEEK%20-%2004.%20Classification%20Algorithm/Module_15.%20Logistic%20Regression%20using%20Scikit%20Learn/__Resources/titanic_data_updated.csv"
df = pd.read_csv(url)
df.sample(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
330,331,yes,third,"McCoy, Miss. Agnes",female,NaN,2,0,367226,23.2500,NaN,Q
679,680,yes,first,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,PC 17755,512.3292,B51 B53 B55,C
482,483,no,third,"Rouse, Mr. Richard Henry",male,50.0,0,0,A/5 3594,8.0500,NaN,S
704,705,no,third,"Hansen, Mr. Henrik Juul",male,26.0,1,0,350025,7.8542,NaN,S
771,772,no,third,"Jensen, Mr. Niels Peder",male,48.0,0,0,350047,7.8542,NaN,S


In [103]:
X = df.drop('Survived', axis=1)
y = df['Survived']

In [104]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

### Numerical

In [105]:
pipleline_1 = Pipeline(
    steps=[
        ('imputer', SimpleImputer(strategy='mean')),
        ("scaler", StandardScaler())
    ]
)
pipleline_1

Pipeline(steps=[('imputer', SimpleImputer()), ('scaler', StandardScaler())])

In [106]:
pipleline_2 = Pipeline(
    steps=[
        ('imputer', SimpleImputer(strategy='median')),
        ("scaler", MinMaxScaler())
    ]
)
pipleline_2

Pipeline(steps=[('imputer', SimpleImputer(strategy='median')),
                ('scaler', MinMaxScaler())])

### Categorical

In [107]:
pipleline_3 = Pipeline(
    steps=[
        ('imputer', SimpleImputer(strategy='most_frequent')),
        ("scaler", StandardScaler())
    ]
)
pipleline_3

Pipeline(steps=[('imputer', SimpleImputer(strategy='most_frequent')),
                ('scaler', StandardScaler())])

In [108]:
pipleline_3 = Pipeline(
    steps=[
        ('imputer', SimpleImputer(strategy='most_frequent')),
        ("encoder", OneHotEncoder(sparse_output=False, drop='first', handle_unknown='ignore'))
    ]
)
pipleline_3

Pipeline(steps=[('imputer', SimpleImputer(strategy='most_frequent')),
                ('encoder',
                 OneHotEncoder(drop='first', handle_unknown='ignore',
                               sparse_output=False))])

In [109]:
categories = [['third', 'second', 'first']]

pipleline_4 = Pipeline(
    steps=[
        ('imputer', SimpleImputer(strategy='most_frequent')),
        ("encoder", OrdinalEncoder(categories=categories)),
        ("scaler", MinMaxScaler())
    ]
)
pipleline_4

Pipeline(steps=[('imputer', SimpleImputer(strategy='most_frequent')),
                ('encoder',
                 OrdinalEncoder(categories=[['third', 'second', 'first']])),
                ('scaler', MinMaxScaler())])

# Preprocessor


In [110]:
preprocessor = ColumnTransformer(
    transformers=[
        ('pipeline_1', pipleline_1, ['Age']),
        ('pipeline_2', pipleline_2, ['Fare']),
        ('pipeline_3', pipleline_3, ['Embarked', 'Sex', 'Cabin']),
        ('pipeline_4', pipleline_4, ['Pclass'])
    ],
    remainder='drop'
)
preprocessor

ColumnTransformer(transformers=[('pipeline_1',
                                 Pipeline(steps=[('imputer', SimpleImputer()),
                                                 ('scaler', StandardScaler())]),
                                 ['Age']),
                                ('pipeline_2',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='median')),
                                                 ('scaler', MinMaxScaler())]),
                                 ['Fare']),
                                ('pipeline_3',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('encoder',
                                                  OneHotEncoder(drop='first',
                                                                handle_unknown='ignore',
                                                                sparse_output=False))]),
                                 ['Embarked', 'Sex', 'Cabin']),
                                ('pipeline_4',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('encoder',
                                                  OrdinalEncoder(categories=[['third',
                                                                              'second',
                                                                              'first']])),
                                                 ('scaler', MinMaxScaler())]),
                                 ['Pclass'])])

## Model Train

In [111]:
log_reg_model = Pipeline(
    steps=[
        ('preprocessor', preprocessor),
        ('model', LogisticRegression(class_weight='balanced', max_iter=1000))
    ]
)
log_reg_model

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('pipeline_1',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer()),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['Age']),
                                                 ('pipeline_2',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   MinMaxScaler())]),
                                                  ['Fare']),
                                                 ('pipeline_3',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_freque...
                                                                   OneHotEncoder(drop='first',
                                                                                 handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  ['Embarked', 'Sex', 'Cabin']),
                                                 ('pipeline_4',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OrdinalEncoder(categories=[['third',
                                                                                               'second',
                                                                                               'first']])),
                                                                  ('scaler',
                                                                   MinMaxScaler())]),
                                                  ['Pclass'])])),
                ('model',
                 LogisticRegression(class_weight='balanced', max_iter=1000))])

#### Lable Encoding.

In [112]:
le = LabelEncoder()
le.fit(y_train)
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [113]:
log_reg_model.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('pipeline_1',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer()),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['Age']),
                                                 ('pipeline_2',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   MinMaxScaler())]),
                                                  ['Fare']),
                                                 ('pipeline_3',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_freque...
                                                                   OneHotEncoder(drop='first',
                                                                                 handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  ['Embarked', 'Sex', 'Cabin']),
                                                 ('pipeline_4',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OrdinalEncoder(categories=[['third',
                                                                                               'second',
                                                                                               'first']])),
                                                                  ('scaler',
                                                                   MinMaxScaler())]),
                                                  ['Pclass'])])),
                ('model',
                 LogisticRegression(class_weight='balanced', max_iter=1000))])

In [114]:
log_reg_model['model'].coef_

array([[-0.44698889,  0.09910199,  0.20886134, -0.44673666, -2.42704591,
        -0.42052213,  0.06896223, -0.41903983,  0.42336263,  0.79259839,
        -0.41377839,  0.48163648,  0.35687468, -0.42040822,  0.2072611 ,
        -0.36566009, -0.26252798, -0.34447668,  0.28723189, -0.41755444,
         0.08397223, -0.2472656 ,  0.03877409,  0.06916923,  0.20852157,
         0.08179128, -0.29615691,  0.03258438, -0.33314038,  0.03083896,
         0.06128005,  0.04161036,  0.02771683,  0.03465699,  0.30088628,
        -0.39992218,  0.05207219, -0.44561173,  0.11055513,  0.0571872 ,
         0.0573157 ,  0.03799738,  0.09003145, -0.40400186, -0.52085958,
        -0.35998987,  0.46147932,  0.55824376,  0.37713246, -0.32358857,
        -0.45117517,  0.06748167, -0.67562684,  0.19396553,  0.05761372,
         0.26245928,  0.04510147, -0.44067528, -0.24458785,  0.04620392,
         0.04767209, -0.38726933,  0.28651796, -0.67082313,  0.36389582,
         0.03243082,  0.02566287, -0.5186305 ,  0.0

In [115]:
log_reg_model['model'].intercept_

array([1.95124021])

In [116]:
log_reg_model['model'].classes_

array([0, 1])

####

In [118]:
y_pred = log_reg_model.predict(X_test) # threshold = 0.5

/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [2] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(


#### Metrics | Confusion Matrix

In [120]:
from sklearn.metrics import accuracy_score,precision_score,recall_score

In [125]:
accuracy = accuracy_score(y_test, y_pred)
print("accuracy : ", accuracy)
precision = precision_score(y_test, y_pred)
print("precision : ", precision)
recall = recall_score(y_test, y_pred)
print("Recall : ", recall)

accuracy :  0.7541899441340782
precision :  0.6582278481012658
Recall :  0.7536231884057971
