In [2]:
import numpy as np

In [5]:
arr = np.random.randint(1, 100, (10, 5)) # Sample - 10, Feature - 5
print(arr)

[[21 63 93 35 94]
 [14 72 21 33 30]
 [88 58 18 18 30]
 [69 44 66 59 31]
 [42 24 21 37 22]
 [77 76 92 79  2]
 [11 47 59 59 23]
 [68 38 49  6 60]
 [78 20 54 80 71]
 [67 66 90 23 54]]


In [7]:
arr.shape

(10, 5)

In [13]:
b = arr.reshape(5, 10)
print(b.shape)
print(b.ndim)
print(b)

(5, 10)
2
[[21 63 93 35 94 14 72 21 33 30]
 [88 58 18 18 30 69 44 66 59 31]
 [42 24 21 37 22 77 76 92 79  2]
 [11 47 59 59 23 68 38 49  6 60]
 [78 20 54 80 71 67 66 90 23 54]]


In [15]:
# Row - wise

flatten = b.flatten()
print(flatten.ndim)
print(flatten)

[21 63 93 35 94 14 72 21 33 30 88 58 18 18 30 69 44 66 59 31 42 24 21 37
 22 77 76 92 79  2 11 47 59 59 23 68 38 49  6 60 78 20 54 80 71 67 66 90
 23 54]
1


In [19]:
# Column - wise

column_wise_flatten = np.ravel(b, order="F")
print(column_wise_flatten)


row_wise_flatten = np.ravel(b, order="C")
print(row_wise_flatten)

[21 88 42 11 78 63 58 24 47 20 93 18 21 59 54 35 18 37 59 80 94 30 22 23
 71 14 69 77 68 67 72 44 76 38 66 21 66 92 49 90 33 59 79  6 23 30 31  2
 60 54]
[21 63 93 35 94 14 72 21 33 30 88 58 18 18 30 69 44 66 59 31 42 24 21 37
 22 77 76 92 79  2 11 47 59 59 23 68 38 49  6 60 78 20 54 80 71 67 66 90
 23 54]


In [22]:
a = np.random.randint(1, 100, (2, 3))
b = np.random.randint(20, 30, (2, 3))

print(a)
print("-----------------------")
print(b)

[[16 12 61]
 [88 63 30]]
-----------------------
[[21 28 26]
 [22 20 23]]


# Concatenate

In [33]:
con_row = np.concatenate((a, b), axis=0) # ROW-Wise
print(con_row)
print("----------------------------")
con_col = np.concatenate((a, b), axis=1) # Column-Wise
print(con_col)




# ERROR

# Row-Wise = Column should be same size.
# Column-Wise = Row should be same size.


x = np.random.randint(1, 10, (2, 3))
y = np.random.randint(20, 30, (2, 4))



r = np.concatenate((x, y), axis=1)
print(r)
r = np.concatenate((x, y), axis=0)
print(r)

[[16 12 61]
 [88 63 30]
 [21 28 26]
 [22 20 23]]
----------------------------
[[16 12 61 21 28 26]
 [88 63 30 22 20 23]]
[[ 3  9  2 27 22 29 28]
 [ 8  4  2 26 22 25 25]]


ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 4

# Transpose Matrix

In [32]:
mat = np.array([
    [10, 20, 30],
    [30, 40, 50]
])
print(mat)

print("---------------------------")

transpose = mat.T
print(transpose)

[[10 20 30]
 [30 40 50]]
---------------------------
[[10 30]
 [20 40]
 [30 50]]


In [55]:
a = np.random.randint(1, 10, (10))
print(a)
splited_aarr = np.array_split(a, 3)
print(splited_aarr)


# Equal division
b = np.random.randint(1, 10, (50,))
print(b)
print("----------------------------------")
splited_barr = np.split(b, 2)
print(splited_barr)

[1 1 9 5 1 7 6 9 1 7]
[array([1, 1, 9, 5]), array([1, 7, 6]), array([9, 1, 7])]
[1 5 3 4 2 2 4 8 9 4 9 4 3 3 3 8 4 4 2 9 3 4 2 7 1 7 4 6 9 8 5 2 2 3 8 6 4
 8 6 3 8 6 9 7 3 8 5 3 3 5]
----------------------------------
[array([1, 5, 3, 4, 2, 2, 4, 8, 9, 4, 9, 4, 3, 3, 3, 8, 4, 4, 2, 9, 3, 4,
       2, 7, 1]), array([7, 4, 6, 9, 8, 5, 2, 2, 3, 8, 6, 4, 8, 6, 3, 8, 6, 9, 7, 3, 8, 5,
       3, 3, 5])]


In [57]:
x = np.array([10, 20, 30])
y = np.array ([40, 50, 60])
print(x+y)
print(np.add(x, y))

[50 70 90]
[50 70 90]


In [63]:
sin_val = np.sin(x)
print(sin_val)
cos_val = np.cos(x)
print(cos_val)

degree = np.rad2deg(sin_val) # deg2rad
print(degree)

base_10_log_val = np.log10(x)
print(base_10_log_val)

[-0.54402111  0.91294525 -0.98803162]
[-0.83907153  0.40808206  0.15425145]
[-31.17011362  52.30790979 -56.61004209]
[1.         1.30103    1.47712125]


In [69]:
# Logical Function

x = np.array([10, 20, 30, 40, 100])
y = np.array([50, 70, 80, 90, 100])
ans = x > y
print(ans)

result= x == y
print(result)



print(np.all(ans))
print(np.any(result))



[False False False False False]
[False False False False  True]
False
True


In [80]:
# Sorting (Inplace) :
x = np.array([10, 8, 18, 16, 100])
z = x.copy()
z.sort()
print(x)
print(z)

# Copy Sorting :
print(x)
sorted = np.sort(x)
print(sorted)
print("___________________________________")
print()

# 2D

mat = np.array([
    [10, 3, 5],
    [8, 4, 9]
    ])

# horizontal axis = 1
horizon_sort = np.sort(mat, axis=1)
print(horizon_sort)

print("--------------")


# vertical axis = 0
vertical_sort = np.sort(mat, axis=0)
print(vertical_sort)

[ 10   8  18  16 100]
[  8  10  16  18 100]
[ 10   8  18  16 100]
[  8  10  16  18 100]
___________________________________

[[ 3  5 10]
 [ 4  8  9]]
--------------
[[ 8  3  5]
 [10  4  9]]


In [92]:
# Searching :
# np.where(condition, x, y) if True : x, otherwise replace with y

print(x)
index = np.where(x==16)
print(index)
print()

index = np.where(x>8)
print(index)
print()

index = np.where(x>8, x, -1)
print(index)
print()


print(mat)
index = np.where(mat>8)
print(index)
print()

index = np.where(mat>8, mat, -1)
print(index)

[ 10   8  18  16 100]
(array([3]),)

(array([0, 2, 3, 4]),)

[ 10  -1  18  16 100]

[[10  3  5]
 [ 8  4  9]]
(array([0, 1]), array([0, 2]))

[[10 -1 -1]
 [-1 -1  9]]


In [97]:
# Counting :
print(x)
maximum_value_index = np.argmax(x)
mini = np.argmin(x)
print(maximum_value_index)
print(mini)

[ 10   8  18  16 100]
4
1


In [113]:
# Counting :

a = np.random.randint(1, 100, (100))
print(a)

valGret60 = np.count_nonzero(a==50)
print(valGret60)

unique_val, count = np.unique(a, return_counts=True)
print(unique_val)
print(count)

[31 88 44 25 26 70 50 43 37 85 74 49 32 74 49 17 22 66 24 18 29 62 73 42
 56 37  1 88  9 60 22 44 22 50  7 98  1 21 13 28 35 88 31 77 50 79  9 33
  3 16 26 77 65 80 31  8  6 70 51 60 45 63  6 43 93 38 54 57 44 27 71 19
 70 51 27 99  8 12 78 69 88 94 70 50 55 50 68 47 48 55 43 64 76 43 47 82
 78 83 87 13]
5
[ 1  3  6  7  8  9 12 13 16 17 18 19 21 22 24 25 26 27 28 29 31 32 33 35
 37 38 42 43 44 45 47 48 49 50 51 54 55 56 57 60 62 63 64 65 66 68 69 70
 71 73 74 76 77 78 79 80 82 83 85 87 88 93 94 98 99]
[2 1 2 1 2 2 1 2 1 1 1 1 1 3 1 1 2 2 1 1 3 1 1 1 2 1 1 4 3 1 2 1 2 5 2 1 2
 1 1 2 1 1 1 1 1 1 1 4 1 1 2 1 2 2 1 1 1 1 1 1 4 1 1 1 1]


# Statistical Methods

In [15]:
data = np.genfromtxt('/content/sample_data/student_scores.csv', delimiter=',', skip_header=True)

math_marks = data[::, :1]
print(math_marks.T)

max_math_marks = np.max(math_marks)
print(max_math_marks)

min_math_marks = np.min(math_marks)
print(min_math_marks)

average_math_marks = np.mean(math_marks)
print(average_math_marks)

median_math_marks = np.median(math_marks)
print(median_math_marks)

std_math_marks = np.std(math_marks)
print(std_math_marks)

[[78. 56. 89. 45. 70. 92. 61. 55. 88. 74. 66. 80. 59. 73. 91. 68. 77. 84.
  62. 95.]]
95.0
45.0
73.15
73.5
13.788672887555204


In [19]:
study_hour = np.array([2, 4, 5, 7, 8])
exam_hour = np.array([65, 75, 78, 88, 92])

data = np.array([study_hour, exam_hour])

correlation = np.corrcoef(data)
print("Correlation Matrix:\n", correlation)

Correlation Matrix:
 [[1.         0.99859154]
 [0.99859154 1.        ]]


In [28]:
# Linear Algebra :

A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

B = np.array([
    [7, 8],
    [9, 10],
    [11, 12]
])

dot_product = np.dot(A, B)
print(dot_product)

print(np.trace(B)) # Diagonal Sum.


sq_mat = np.array([
    [1, 24, 3],
    [4, 51, 6],
    [7, 82, 9]
])

det_of_sq_mat = np.linalg.det(sq_mat)
print(det_of_sq_mat)

rank_of_sq_mat = np.linalg.matrix_rank(sq_mat)
print(rank_of_sq_mat)

[[ 58  64]
 [139 154]]
17
24.000000000000036
3


In [37]:
a = np.array([1, 2, 3, 4, 5, 6])
b = a.reshape(2, 3)
print(b.shape)
print(b)

np.sin(np.pi/2)
print(np.sort(a))

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print(np.dot(A, B))

(2, 3)
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[[19 22]
 [43 50]]


## Practice



###
1 . Create a 1D, 2D, and 3D NumPy array and print their dimensions and shapes.







In [42]:
# 1
oneD = np.array([1, 2, 3])
twoD = np.array([[1, 2, 3], [4, 5, 6]])
threeD = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],

    [
        [7, 9, 9],
        [3, 4, 6]
    ]
])

print(oneD.ndim)
print(twoD.ndim)
print(threeD.ndim)
print(oneD.shape)
print(twoD.shape)
print(threeD.shape)


1
2
3
(3,)
(2, 3)
(2, 2, 3)



2 . Create:
*   an array of zeros of shape (3,3)
*   an array of ones of shape (2,5)
*   an array filled with 7


In [47]:
a = np.zeros((3, 3))
b = np.ones((2, 5))
c = np.full((2, 5), 7)

print(a)
print(b)
print(c)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[7 7 7 7 7]
 [7 7 7 7 7]]


3 . Create an array of even numbers between 10 and 50 using arange.


In [48]:
a = np.arange(10, 50, 2)
print(a)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


4 . Create a 4×4 matrix from 0–15. Then , extract:
* the first row
* the last column
* a 2×2 subarray from the center


In [58]:
b = np.arange(16).reshape(4, 4)
print(b)
print()

first_row = b[:1, :]
print(first_row)
print()

last_col = b[:, 3:]
print(last_col)
print()

subarry = b[1:3, 1:3]
print(subarry)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

[[0 1 2 3]]

[[ 3]
 [ 7]
 [11]
 [15]]

[[ 5  6]
 [ 9 10]]
